### ISSUE TITLE
Driver [weibo] not supported.

### ISSUE THREAD

**Issue by ivanzhang** [SocialiteProviders/Weibo#1]
this error occurs on laravel 5.1, i just tested

**Comment by DraperStudio** [comment]
Works without any issues if you do everything like it is instructed in the documentation.

Any code?

**Comment by boorzhang** [comment]
sorry, it works

**Comment by ivanzhang** [comment]
sorry, it works

**Comment by ivanzhang** [comment]
i didn't test it properly.
