### ISSUE TITLE
This package doesn't compile with Laravel\Socialite\Contract

### ISSUE THREAD

**Issue by fzhan** [SocialiteProviders/Weibo#2]
See:

```
<?php namespace Laravel\Socialite\Contracts;

interface User
{

    /**
     * Get the unique identifier for the user.
     *
     * @return string
     */
    public function getId();

    /**
     * Get the nickname / username for the user.
     *
     * @return string
     */
    public function getNickname();

    /**
     * Get the full name of the user.
     *
     * @return string
     */
    public function getName();

    /**
     * Get the e-mail address of the user.
     *
     * @return string
     */
    public function getEmail();

    /**
     * Get the avatar / image URL for the user.
     *
     * @return string
     */
    public function getAvatar();
}
```
Where getID and getEmail is not presented.

**Comment by DraperStudio** [comment]
Our Providers are fully compliant with Socialite. This Interface is for the User Class which creates the User Object with all details.

https://github.com/laravel/socialite/blob/2.0/src/AbstractUser.php

**Comment by fzhan** [comment]
@DraperStudio sorry I wasn't clear,

```
    /**
     * {@inheritdoc}.
     */
    protected function mapUserToObject(array $user)
    {
        return (new User())->setRaw($user)->map([
            'id' => $user['idstr'], 'nickname' => $user['name'],
            'avatar' => $user['avatar_large'], 'name' => null, 'email' => null,
        ]);
    }
```

There are functions for getting the name and email, perhaps we could improve on this API?

Thanks

**Comment by DraperStudio** [comment]
How would you want to improve on that? It just creates a new User instance and maps the given values to it which then can be accessed via the getter-methods.

```php
protected function mapUserToObject(array $user)
{
    return (new User())->setRaw($user)->map([
        'id' => $user['idstr'], // getId()
        'nickname' => $user['name'], // getNickname()
        'name' => null, // getName()
        'email' => null, // getEmail()
        'avatar' => $user['avatar_large'], // getAvatar()
    ]);
}
```

This is how Socialite is built and if you want any changes to that you will need to create a proposal at the [laravel/socialite](https://github.com/laravel/socialite) repository or a pull-request with your changes. But I doubt that Taylor will change the API any time soon since it is clean, simple and does the job it is supposed to do.

**Comment by fzhan** [comment]
Okay, weibo is tricky, the email field doesn't return unless your application pass their manual verification. So instead of simply returning email as null, I did something like this:
```
    protected function getEmail($token)
    {
        $response = $this->getHttpClient()->get('https://api.weibo.com/2/account/profile/email.json', [
            'query' => ['access_token' => $token],
        ]);

        return json_decode($response->getBody(), true)['email'];
    }
```
It will return the email once oAuth application gets approval from Sina. Without approval the application is meaningless, so email is good to have.

If it would be too much trouble, I can do a pull request.

**Comment by DraperStudio** [comment]
If you have verified that it is working you can send a pull-request.

Best would be if you post the result of `dd(Socialize::with('weibo')->user());` so I can see the resulting User Object.
